POST http://localhost:3000/campaigns

{
    "Name": "mouse 23",
	"Content": "change password",
	"emails":  ["teste@teste.com.br"]
}

###
GET http://localhost:3000/campaigns/d3ru2vf3bvl3ru23qf90

###
PATCH http://localhost:3000/campaigns/cancel/d3ru2vf3bvl3ru23qf90

###
DELETE http://localhost:3000/campaigns/delete/d3ru2vf3bvl3ru23qf90